PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE Users (id INTEGER AUTO_INCREMENT, username TEXT, password TEXT);
INSERT INTO Users VALUES(0,'admin','5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8');
INSERT INTO Users VALUES(1,'username','password');
CREATE TABLE Hosts (id INTEGER AUTO_INCREMENT, hostid INTEGER, hostname TEXT, uname TEXT);
CREATE TABLE Commands (id INTEGER AUTO_INCREMENT, commandid INTEGER, hostid INTEGER, pending BOOLEAN, timestamp DATETIME DEFAULT CURRENT_TIMESTAMP, command TEXT, stdout TEXT);
COMMIT;
